--------------------------------------------------------
-- Archivo creado  - jueves-agosto-28-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASIGNACIONES
--------------------------------------------------------

  CREATE TABLE "SUAF"."ASIGNACIONES" 
   (	"ASIGNACION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"OBJETO_ID" NUMBER, 
	"DESARROLLADOR_ID" NUMBER, 
	"FECHA_ASIGNACION" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"FECHA_LIBERACION" TIMESTAMP (6), 
	"COMENTARIO_ASIGNACION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SUAF.ASIGNACIONES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ASIGNACIONES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUAF"."PK_ASIGNACIONES" ON "SUAF"."ASIGNACIONES" ("ASIGNACION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ASIGNACIONES
--------------------------------------------------------

  ALTER TABLE "SUAF"."ASIGNACIONES" MODIFY ("ASIGNACION_ID" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ASIGNACIONES" MODIFY ("OBJETO_ID" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ASIGNACIONES" MODIFY ("DESARROLLADOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ASIGNACIONES" MODIFY ("FECHA_ASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ASIGNACIONES" ADD CONSTRAINT "PK_ASIGNACIONES" PRIMARY KEY ("ASIGNACION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASIGNACIONES
--------------------------------------------------------

  ALTER TABLE "SUAF"."ASIGNACIONES" ADD CONSTRAINT "FK_ASIGNACION_OBJETO" FOREIGN KEY ("OBJETO_ID")
	  REFERENCES "SUAF"."OBJETOS" ("OBJETO_ID") ENABLE;
  ALTER TABLE "SUAF"."ASIGNACIONES" ADD CONSTRAINT "FK_ASIGNACION_DEV" FOREIGN KEY ("DESARROLLADOR_ID")
	  REFERENCES "SUAF"."DESARROLLADORES" ("DESARROLLADOR_ID") ENABLE;
