--------------------------------------------------------
--  DDL for Table CHAINED_ROWS
--------------------------------------------------------

  CREATE TABLE "SUAF"."CHAINED_ROWS" 
   (	"OWNER_NAME" VARCHAR2(30 BYTE), 
	"TABLE_NAME" VARCHAR2(30 BYTE), 
	"CLUSTER_NAME" VARCHAR2(30 BYTE), 
	"PARTITION_NAME" VARCHAR2(30 BYTE), 
	"SUBPARTITION_NAME" VARCHAR2(30 BYTE), 
	"HEAD_ROWID" ROWID, 
	"ANALYZE_TIMESTAMP" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 10485760 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
