--------------------------------------------------------
--  DDL for Table DEPURACION_RUBP
--------------------------------------------------------

  CREATE TABLE "SUAF"."DEPURACION_RUBP" 
   (	"CUB" NUMBER(10,0), 
	"TIPO_DOCUMENTO" NUMBER(2,0), 
	"NRO_DOCUMENTO" VARCHAR2(15 BYTE), 
	"DENOMINACION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
