--------------------------------------------------------
--  DDL for Table DESARROLLADORES
--------------------------------------------------------

  CREATE TABLE "SUAF"."DESARROLLADORES" 
   (	"DESARROLLADOR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"EQUIPO" VARCHAR2(50 BYTE), 
	"ACTIVO" CHAR(1 BYTE) DEFAULT 'S'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index PK_DESARROLLADORES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUAF"."PK_DESARROLLADORES" ON "SUAF"."DESARROLLADORES" ("DESARROLLADOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  Constraints for Table DESARROLLADORES
--------------------------------------------------------

  ALTER TABLE "SUAF"."DESARROLLADORES" MODIFY ("DESARROLLADOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."DESARROLLADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."DESARROLLADORES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."DESARROLLADORES" ADD CHECK (activo IN ('S','N')) ENABLE;
  ALTER TABLE "SUAF"."DESARROLLADORES" ADD CONSTRAINT "PK_DESARROLLADORES" PRIMARY KEY ("DESARROLLADOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SUAF"."DESARROLLADORES" ADD CONSTRAINT "UK_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  
  
  --------------------------------------------------------
--  DDL for Index UK_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUAF"."UK_EMAIL" ON "SUAF"."DESARROLLADORES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

