--------------------------------------------------------
--  DDL for Table ESQUEMAS
--------------------------------------------------------

  CREATE TABLE "SUAF"."ESQUEMAS" 
   (	"ESQUEMA_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_ESQUEMA" VARCHAR2(30 BYTE), 
	"AMBIENTE" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index PK_ESQUEMAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUAF"."PK_ESQUEMAS" ON "SUAF"."ESQUEMAS" ("ESQUEMA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  --------------------------------------------------------
--  DDL for Index UK_ESQUEMA_AMB
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUAF"."UK_ESQUEMA_AMB" ON "SUAF"."ESQUEMAS" ("NOMBRE_ESQUEMA", "AMBIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  Constraints for Table ESQUEMAS
--------------------------------------------------------

  ALTER TABLE "SUAF"."ESQUEMAS" MODIFY ("ESQUEMA_ID" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ESQUEMAS" MODIFY ("NOMBRE_ESQUEMA" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ESQUEMAS" MODIFY ("AMBIENTE" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ESQUEMAS" ADD CHECK (ambiente IN ('DESA','TEST','FINCACP','PROD')) ENABLE;
  ALTER TABLE "SUAF"."ESQUEMAS" ADD CONSTRAINT "PK_ESQUEMAS" PRIMARY KEY ("ESQUEMA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SUAF"."ESQUEMAS" ADD CONSTRAINT "UK_ESQUEMA_AMB" UNIQUE ("NOMBRE_ESQUEMA", "AMBIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

