--------------------------------------------------------
--  Constraints for Table ESQUEMAS
--------------------------------------------------------

  ALTER TABLE "SUAF"."ESQUEMAS" MODIFY ("ESQUEMA_ID" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ESQUEMAS" MODIFY ("NOMBRE_ESQUEMA" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ESQUEMAS" MODIFY ("AMBIENTE" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ESQUEMAS" ADD CHECK (ambiente IN ('DESA','TEST','FINCACP','PROD')) ENABLE;
  ALTER TABLE "SUAF"."ESQUEMAS" ADD CONSTRAINT "PK_ESQUEMAS" PRIMARY KEY ("ESQUEMA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SUAF"."ESQUEMAS" ADD CONSTRAINT "UK_ESQUEMA_AMB" UNIQUE ("NOMBRE_ESQUEMA", "AMBIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
