--------------------------------------------------------
-- Archivo creado  - jueves-agosto-28-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ESTADOS
--------------------------------------------------------

  CREATE TABLE "SUAF"."ESTADOS" 
   (	"ESTADO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_ESTADO" VARCHAR2(30 BYTE), 
	"ES_EDITABLE" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SUAF.ESTADOS
SET DEFINE OFF;
Insert into SUAF.ESTADOS (ESTADO_ID,NOMBRE_ESTADO,ES_EDITABLE) values ('1','DISPONIBLE','S');
Insert into SUAF.ESTADOS (ESTADO_ID,NOMBRE_ESTADO,ES_EDITABLE) values ('2','EN_DESARROLLO','S');
Insert into SUAF.ESTADOS (ESTADO_ID,NOMBRE_ESTADO,ES_EDITABLE) values ('3','EN_REVISION','N');
Insert into SUAF.ESTADOS (ESTADO_ID,NOMBRE_ESTADO,ES_EDITABLE) values ('4','EN_TEST','N');
Insert into SUAF.ESTADOS (ESTADO_ID,NOMBRE_ESTADO,ES_EDITABLE) values ('5','APROBADO','N');
Insert into SUAF.ESTADOS (ESTADO_ID,NOMBRE_ESTADO,ES_EDITABLE) values ('6','EN_PROD','N');
Insert into SUAF.ESTADOS (ESTADO_ID,NOMBRE_ESTADO,ES_EDITABLE) values ('7','OBSOLETO','N');
--------------------------------------------------------
--  DDL for Index PK_ESTADOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUAF"."PK_ESTADOS" ON "SUAF"."ESTADOS" ("ESTADO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_NOMBRE_ESTADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUAF"."UK_NOMBRE_ESTADO" ON "SUAF"."ESTADOS" ("NOMBRE_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ESTADOS s
--------------------------------------------------------

  ALTER TABLE "SUAF"."ESTADOS" MODIFY ("ESTADO_ID" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ESTADOS" MODIFY ("NOMBRE_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SUAF"."ESTADOS" ADD CHECK (es_editable IN ('S','N')) ENABLE;
  ALTER TABLE "SUAF"."ESTADOS" ADD CONSTRAINT "PK_ESTADOS" PRIMARY KEY ("ESTADO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SUAF"."ESTADOS" ADD CONSTRAINT "UK_NOMBRE_ESTADO" UNIQUE ("NOMBRE_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
