--------------------------------------------------------
-- Archivo creado  - jueves-agosto-28-2025   
--------------------------------------------------------
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\CHAINED_ROWS.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\DEPURACION_RUBP.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\DESARROLLADORES.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\ESQUEMAS.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\PK_DESARROLLADORES.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\UK_EMAIL.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\PK_ESQUEMAS.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\UK_ESQUEMA_AMB.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\DESARROLLADORES_CONSTRAINT.sql
@D:\GITHUB\SUAF_DESA_2\desa\TABLAS\ESQUEMAS_CONSTRAINT.sql
xxxxxx
